# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-22 15:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20160522_0952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_image_B',
        ),
        migrations.RemoveField(
            model_name='book',
            name='book_image_G',
        ),
        migrations.RemoveField(
            model_name='book',
            name='book_image_R',
        ),
    ]
